### ISSUE TITLE
Great job simplifying CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [javajen77/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code. There are a few shared properties that you can simplify by applying to multiple selectors at once, rather than individually. 

Consider simplifying the CSS code further for the font-weight property as well, which several selectors share.

**Comment by javajen77** [comment]
Thank you for your review. In simplifying CSS code, is it considered best practice to reference an element multiple times (h2, p, class etc), and reference the style as little as possible? Or is it better to reference an element fewer times and the style more frequently?

Thanks,
Jen

**Comment by josephtkim** [comment]
Hi Jen,

You want to reference an element as few times as possible, and only reference them again when listing multiple selectors that share a property. Usually, it would be best to reference the style as little as possible, so you can technically say it has priority over the elements, especially if you know that multiple selectors will share the same property anyway. This way, you only need to change the property value in one location, rather than for each selector individually.

This article might also be helpful to explain the reasoning for simplification: https://www.thoughtco.com/grouping-multiple-css-selectors-3467065

Here is a quick illustration,

Referencing the element fewer times and style more frequently:
```css
h1 {
  font-family: Helvetica;
  font-weight: bold;
}

h2 {
  font-family: Helvetica;
  font-size: 32px;
}

h3 {
  font-family: Helvetica;
  color: blue;
}
```

Referencing the element multiple times and the style as little as possible:
```css
h1, h2, h3 {
  font-family: Helvetica;
}

h1 {
  font-weight: bold;
}

h2 {
  font-size: 32px;
}

h3 {
  color: blue;
}
```

The latter is preferred, especially if you had to change the font-family for whatever reason for all the elements, so you only have to change it one time.
